version: '3.8'
services:
    instashare-front:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'npm start'
        volumes:
            - .:/usr/src/app
        ports:
            - 8001:8000
        networks:
            - instashare
            
networks:
    instashare:
      external:
        name: instashare
